# This is a generated file. Not intended for manual editing.
services:
  ifsp.api:
    build:
      context: "C:\\Projetos\\Github\\Ifsp.Api"
      dockerfile: "Ifsp.Api/Dockerfile"
      target: "base"
      args:
        BUILD_CONFIGURATION: "Debug"
    command: []
    entrypoint:
    - "/opt/JetBrains/RiderDebuggerTools/linux-x64/JetBrains.Debugger.Worker"
    - "--runtimeconfig"
    - "/opt/JetBrains/RiderDebuggerTools/JetBrains.Debugger.Worker.runtimeconfig.json"
    - "--mode=server"
    - "--frontend-port=57000"
    - "--backend-port=57200"
    - "--roslyn-worker-port=57400"
    - "--timeout=60"
    environment:
      DOTNET_USE_POLLING_FILE_WATCHER: "true"
      RIDER_DEBUGGER_LOG_DIR: "/var/opt/JetBrains/RiderDebuggerTools"
      RESHARPER_LOG_CONF: "/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    image: "ifsp.api:dev"
    ports:
    - "127.0.0.1:57011:57000"
    - "127.0.0.1:57211:57200"
    - "127.0.0.1:57411:57400"
    volumes:
    - "C:\\Projetos\\Github\\Ifsp.Api\\Ifsp.Api:/app:rw"
    - "C:\\Projetos\\Github\\Ifsp.Api:/src:rw"
    - "C:\\Users\\jc_md\\.nuget\\packages:/home/app/.nuget/packages"
    - "C:\\Users\\jc_md\\AppData\\Local\\JetBrains\\RiderRemoteDebugger\\2024.3.8\\\
      Linux64:/opt/JetBrains/RiderDebuggerTools"
    - "C:\\Users\\jc_md\\AppData\\Local\\JetBrains\\Installations\\Rider243\\bin\\\
      backend-log.xml:/etc/opt/JetBrains/RiderDebuggerTools/backend-log.xml"
    - "C:\\Users\\jc_md\\AppData\\Local\\JetBrains\\Rider2024.3\\log\\DebuggerWorker\\\
      JetBrains.Debugger.Worker.2025_5_23_23_11_54:/var/opt/JetBrains/RiderDebuggerTools:rw"
    working_dir: "/app"
