services:
  ifsp.api:
    image: ifsp.api
    build:
      context: .
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - OpenAi__BaseUrl=
      - OpenAi__ApiKey=
